name: Automatically deploy new tag onto github pages

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy new version
    runs-on: ubuntu-latest
    env:
      CI: ''
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: deploy with gh-pages
        run: npm run deploy
