name: Automatically deploy new version on github pages

on:
  push:
    branches:
      - 'master'

jobs:
  build-deploy:
    name: Create and publish new release
    runs-on: ubuntu-latest
    env:
      CI: '' # temporaly disable because @memgraph/orb throws warnings on build and on CI warnings acts like errors
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Check if version in package.json has changed
      - name: check version
        run: |
          echo "DIFF=$(git show --format= --minimal -U0 -1 package.json | grep -E '\"version\":\s+\"[0-9\.]+\"' | wc -l)" >> $GITHUB_ENV

      - name: Setup node.js
        if: env.DIFF == '2'
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - name: npm install
        if: env.DIFF == '2'
        run: npm ci

      - name: deploy with gh-pages
        if: env.DIFF == '2'
        run: npm run deploy
