# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create new GH pages release 

on:
  workflow_dispatch:
    inputs:
      version:
        description: Which version part to update
        required: true
        type: choice
        options:
        - major
        - minor
        - patch
  
jobs:
  release:
    name: Create and publish new release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        cache: 'npm'
        
    - run: git config --global user.email "github-actions@github.com"
    - run: git config --global user.name "github-actions"
    
    - name: npm install
      run: npm ci
      
    - name: npm bump version
      run: npm version ${{ inputs.version }}
      
    - name: GH pages
      run: npm run deploy
    
    - name: Commit bumped version
      run: git commit -m "bumped version"
      
    - name: Push commit
      run: git push --tags
